### ISSUE TITLE
recipe type works fine without "minecraft:"

### ISSUE THREAD

**Issue by ChenCMD** [SPGoding/datapack-json#27]
Currently throws a warning if you do not explicitly state "minecraft:"
![image](https://user-images.githubusercontent.com/46134240/71871430-7bae6380-315c-11ea-8d37-3a0a9471a5dc.png)

**Comment by SPGoding** [comment]
This is hard to fix by now. The whole JSON part of DHP will be combined in the language server in the future. See SPGoding/datapack-language-server#342.
