### ISSUE TITLE
DHP does not fully support 1.14 and 1.15

### ISSUE THREAD

**Issue by akiraveliara** [SPGoding/datapack-json#36]
recipe "type": "minecraft:stonecutting" is not supported
recipe "type": "minecraft:crafting_special_*" are not supported
"item": "minecraft:honey_block" is not supported

**Comment by SPGoding** [comment]
I was planning to merge this project into the main extension but there wasn't any progress since then, and I'm really sorry for that.

 From now on I will just keep updating this repo anyways.
