### ISSUE TITLE
Attributes still use the old format

### ISSUE THREAD

**Issue by Insane96** [SPGoding/datapack-json#47]
Attributes in 1.16 have been renamed to use all lowercase, so e.g. `generic.movementSpeed` has become `generic.movement_speed`

![image](https://user-images.githubusercontent.com/7185104/88475515-d957a100-cf30-11ea-90fb-0e388d4c88da.png)

**Comment by SPGoding** [comment]
This project is no longer maintained in favor of the upcoming new support provided by Data-pack Helper Plus 3.0.0.
