### ISSUE TITLE
src/advancement.json is missing trigger "shot_crossbow"

### ISSUE THREAD

**Issue by dv-extrarius** [SPGoding/datapack-json#48]
As documented on https://minecraft.gamepedia.com/Advancement/JSON_format#minecraft:shot_crossbow , there is a minecraft:shot_crossbow trigger for advancements and it is not present in src/advancement.json

**Comment by SPGoding** [comment]
Thanks for the report, but this repository is no longer maintained. We're trying to move over to [misode/minecraft-schemas](https://github.com/misode/minecraft-schemas) which already has supports for `minecraft:shot_crossbow` :D
